[build]
  command = ""
  publish = "."
  functions = "netlify/functions"

# Redirecciones
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/admin/"
  status = 200

[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200
